"""
scos_bridge.py — Selyrion reasoning ↔ tool execution bridge.

Fully symbolic tool selection — no LLM. Intent is inferred from prompt
keywords, tool calls are built deterministically, code is generated by
selyrion_code_test (pattern retrieval + CMS synthesis), not by an LLM.

Pipeline:
  reason(prompt)
    → _select_tools(prompt)      keyword → tool list
    → _build_calls(prompt, tools) build args (code via run_task)
    → _run_tools(calls)           execute through SCOS registry
    → _format_output(results)     structured summary, no LLM prose

Usage:
    from scos_bridge import SelyrionBridge
    bridge = SelyrionBridge()
    result = bridge.reason("calculate fibonacci(10) and store the result")
    print(result["final_output"])
"""
import json, time, hashlib, sqlite3
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).parent))
import scos_tools
import tools  # auto-registers all tools on import

CLAUDECODE_DB = Path.home() / "claudecode.db"

SEL  = "\033[38;5;141m"
OK   = "\033[32m"
WARN = "\033[33m"
DIM  = "\033[2m"
B    = "\033[1m"
R    = "\033[0m"

# ── Intent keyword maps ────────────────────────────────────────────────────────

_SEARCH_TRIGGERS = {
    "search","find","recall","know","what","chess","position","opening",
    "memory","cms","relation","concept","retrieve","lookup",
}
_CODE_TRIGGERS = {
    "write","run","execute","script","code","compute","calculate",
    "generate","create","make","build","print","show","count","sort",
    "list","fibonacci","factorial","fft","fourier","plot","simulate",
}
_STORE_TRIGGERS = {
    "store","remember","save","record","add to","write to cms","persist","learn",
}


class SelyrionBridge:
    def __init__(self, session_id: str = None):
        self.session_id = session_id or (
            "bridge." + hashlib.md5(str(time.time()).encode()).hexdigest()[:8]
        )
        self.history: list[dict] = []

    # ── Symbolic intent router ─────────────────────────────────────────────────

    def _select_tools(self, prompt: str) -> list[str]:
        """Determine tool sequence from prompt keywords — no LLM."""
        words = set(prompt.lower().split())
        tools_needed = []

        if words & _SEARCH_TRIGGERS:
            tools_needed.append("memory_search")
        if words & _CODE_TRIGGERS:
            tools_needed.append("code_execute")
        if words & _STORE_TRIGGERS:
            tools_needed.append("cms_write")

        return tools_needed or ["memory_search"]

    def _build_calls(self, prompt: str,
                     tool_names: list[str],
                     prior_results: list[dict]) -> list[tuple[str, dict]]:
        """
        Build tool call args deterministically.
        code_execute: uses selyrion_code_test.run_task() to generate code
                      from pattern memory — no LLM involved.
        cms_write:    derives subject/predicate/object from prior code result.
        """
        calls = []
        code_result = None

        for name in tool_names:
            if name == "memory_search":
                # Use full prompt as query; prefer chess domain if chess keywords present
                chess_words = {"chess","position","opening","pawn","move","piece","endgame"}
                domain = "chess" if set(prompt.lower().split()) & chess_words else ""
                calls.append(("memory_search", {
                    "query":  prompt[:120],
                    "domain": domain,
                    "limit":  5,
                }))

            elif name == "code_execute":
                # Generate + validate code symbolically — result is pre-cooked,
                # no re-execution via codeops subprocess needed.
                print(f"  {DIM}[bridge] Selyrion generating code from memory...{R}", flush=True)
                try:
                    from selyrion_code_test import run_task
                    code_result = run_task(prompt)
                    if code_result.get("success") and code_result.get("final_code"):
                        # Mark as pre-run so _run_tools skips codeops re-execution
                        calls.append(("code_execute_prerun", {
                            "code":    code_result["final_code"],
                            "output":  code_result.get("output", ""),
                            "problem": prompt,
                        }))
                    else:
                        reason = code_result.get("reason", "unknown")
                        print(f"  {WARN}[bridge] code synthesis failed: {reason}{R}")
                except Exception as e:
                    print(f"  {WARN}[bridge] run_task error: {e}{R}")

            elif name == "cms_write":
                # Only write if we have a successful code result to record
                if code_result and code_result.get("success"):
                    output = code_result.get("output", "").strip()[:80]
                    if output:
                        calls.append(("cms_write", {
                            "subject":   prompt[:60],
                            "predicate": "produces",
                            "object":    output,
                            "confidence": 0.75,
                            "domain":    "codeops",
                        }))
                # Also check prior memory_search results for relation storage
                elif prior_results:
                    pass  # defer — nothing verified to store yet

        return calls

    # ── Tool execution ─────────────────────────────────────────────────────────

    def _run_tools(self, calls: list[tuple[str, dict]]) -> list[dict]:
        results = []
        for tool_name, args in calls:
            # Pre-validated by run_task — skip codeops re-execution
            if tool_name == "code_execute_prerun":
                out = args.get("output", "").strip()[:80]
                print(f"  {SEL}▶ TOOL:{R} {B}code_execute{R} {OK}[success]{R} → {out}")
                r = {"status": "success", "output": args.get("output", ""), "attempts": 1}
                results.append({"tool": "code_execute", "args": args, "result": r})
                continue

            print(f"  {SEL}▶ TOOL:{R} {B}{tool_name}{R}", end=" ", flush=True)
            r = scos_tools.registry.invoke(tool_name, args, self.session_id)
            status = r.get("status", "?")
            col = OK if status == "success" else WARN
            print(f"{col}[{status}]{R}", end=" ")

            if tool_name == "code_execute":
                if status == "success":
                    out  = r.get("output", "").strip()[:80]
                    att  = r.get("attempts", 1)
                    note = f" (fixed in {att} attempts)" if att > 1 else ""
                    print(f"→ {out}{note}")
                else:
                    print(f"→ {r.get('error_class','?')}:{r.get('subtype','?')}")
            elif tool_name == "memory_search":
                print(f"→ {r.get('count', 0)} relations found")
            elif tool_name == "cms_write":
                print(f"→ {r.get('written', r.get('error', '?'))}")
            else:
                print()

            results.append({"tool": tool_name, "args": args, "result": r})
        return results

    # ── Output formatter ───────────────────────────────────────────────────────

    def _format_output(self, prompt: str, results: list[dict]) -> str:
        parts = [f"Selyrion | {prompt[:60]}"]
        for r in results:
            tool = r["tool"]
            res  = r["result"]
            if tool == "memory_search":
                rels = res.get("relations", [])
                if rels:
                    parts.append(f"\nCMS ({len(rels)} relations):")
                    for rel in rels[:4]:
                        parts.append(
                            f"  {rel.get('subject','')} → "
                            f"{rel.get('predicate','')} → "
                            f"{rel.get('object','')}"
                        )
                else:
                    parts.append("\nCMS: no relations found")
            elif tool == "code_execute":
                if res.get("status") == "success":
                    parts.append(f"\nCode output: {res.get('output','').strip()[:200]}")
                else:
                    parts.append(f"\nCode failed: {res.get('error_class','?')}/{res.get('subtype','?')}")
            elif tool == "cms_write":
                written = res.get("written", "")
                if written:
                    parts.append(f"\nCMS stored: {written}")
        return "\n".join(parts)

    # ── Main entry point ───────────────────────────────────────────────────────

    def reason(self, prompt: str, **_) -> dict:
        """Symbolic reasoning — keyword routing, no LLM."""
        print(f"\n{B}{'─'*60}{R}")
        print(f"  {SEL}{B}Selyrion:{R} {prompt[:80]}")
        print(f"{'─'*60}")

        self.history.append({"role": "user", "content": prompt})

        tool_names = self._select_tools(prompt)
        print(f"  {DIM}[bridge] tools selected: {tool_names}{R}", flush=True)

        calls   = self._build_calls(prompt, tool_names, [])
        results = self._run_tools(calls)
        output  = self._format_output(prompt, results)

        self.history.append({"role": "assistant", "content": output})
        self._log_session(prompt, output, results)

        print(f"\n{'─'*60}")
        return {
            "status":       "complete",
            "final_output": output,
            "tool_results": results,
            "turns":        1,
            "session_id":   self.session_id,
        }

    # ── Session logging ────────────────────────────────────────────────────────

    def _log_session(self, prompt: str, output: str, tool_results: list):
        try:
            conn = sqlite3.connect(CLAUDECODE_DB)
            sid  = "sess." + self.session_id
            conn.execute("""
                INSERT OR IGNORE INTO sessions
                    (id, summary, tools_used, created_at)
                VALUES (?,?,?,?)
            """, (sid, prompt[:200],
                  json.dumps([r["tool"] for r in tool_results]),
                  time.time()))
            conn.commit(); conn.close()
        except Exception:
            pass


# ── CLI ────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("prompt", nargs="?",
                        default="search CMS for chess opening knowledge")
    parser.add_argument("--session", default="")
    args = parser.parse_args()

    bridge = SelyrionBridge(session_id=args.session or None)
    result = bridge.reason(args.prompt)
    print(f"\n{B}Output:{R}\n{result['final_output']}")
    print(f"{DIM}Tools: {[r['tool'] for r in result['tool_results']]}{R}")
